import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import JavaScriptObfuscator from "javascript-obfuscator";
import { minify } from "terser";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

const defaultSource = path.join(os.homedir(), "Documents", "app.js");
const sourcePath = path.resolve(process.env.RTP_APP_SOURCE || defaultSource);
const outputPath = path.resolve(process.env.RTP_APP_OUTPUT || path.join(rootDir, "assets", "app.js"));

async function assertFileExists(filePath, label) {
  try {
    await access(filePath);
  } catch {
    throw new Error(`${label} tidak ditemukan: ${filePath}`);
  }
}

await assertFileExists(sourcePath, "Source app");

const sourceCode = await readFile(sourcePath, "utf8");
const minified = await minify(sourceCode, {
  compress: {
    drop_console: false,
    passes: 2
  },
  format: {
    comments: false
  },
  mangle: {
    toplevel: true
  },
  sourceMap: false,
  toplevel: true
});

if (!minified.code) {
  throw new Error("Minify gagal: output kosong.");
}

const obfuscated = JavaScriptObfuscator.obfuscate(minified.code, {
  compact: true,
  controlFlowFlattening: false,
  deadCodeInjection: false,
  debugProtection: false,
  disableConsoleOutput: false,
  identifierNamesGenerator: "hexadecimal",
  numbersToExpressions: false,
  renameGlobals: true,
  selfDefending: false,
  simplify: true,
  splitStrings: true,
  splitStringsChunkLength: 8,
  stringArray: true,
  stringArrayCallsTransform: true,
  stringArrayEncoding: ["base64"],
  stringArrayRotate: true,
  stringArrayShuffle: true,
  stringArrayThreshold: 0.75,
  target: "browser",
  transformObjectKeys: true,
  unicodeEscapeSequence: false
});

const outputCode = [
  "/* Generated by npm run build:app. Do not edit assets/app.js directly. */",
  obfuscated.getObfuscatedCode(),
  ""
].join("\n");

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, outputCode, "utf8");

const kb = Buffer.byteLength(outputCode, "utf8") / 1024;
console.log(`Built ${path.relative(rootDir, outputPath)} from ${sourcePath}`);
console.log(`Output size: ${kb.toFixed(1)} KB`);
